### ISSUE TITLE
Magic 8-ball unit testing

### ISSUE THREAD

**Issue by wincy02** [cse110-sp23-group14/cse110-sp23-group14#15]
-input in other language other than English
-input of only numbers (12384399523)
-input for only question mark (?)
-input of multiple questions at once

unit testing in JS
// Test empty input
let result = magic8ball('');
console.assert(result === 'Please ask a question', 'Failed: Empty input test');

// Test invalid input
result = magic8ball('123');
console.assert(result === 'Please ask a question', 'Failed: Invalid input test');

// Test unusual input
result = magic8ball('Am I going to win a billion dollars tomorrow???');
console.assert(result !== '', 'Failed: Unusual input test');

// Test performance
let startTime = new Date();
for (let i = 0; i < 1000; i++) {
  result = magic8ball('Will it rain today?');
}
let endTime = new Date();
let elapsedTime = endTime - startTime;
console.assert(elapsedTime < 5000, 'Failed: Performance test');

// Test localization
result = magic8ball('¿Voy a ganar la lotería?');
console.assert(result !== '', 'Failed: Localization test');

// Test customization
result = magic8ball('Will I get a promotion?');
let customResponse = 'It is certain';
addCustomResponse(customResponse);
result = magic8ball('Will I get a promotion?');
console.assert(result === customResponse, 'Failed: Customization test');

// Test empty question
result = magic8ball('  ');
console.assert(result === 'Please ask a question', 'Failed: Empty question test');

// Test too long question
result = magic8ball('Am I going to win a billion dollars tomorrow?'.repeat(50));
console.assert(result !== '', 'Failed: Too long question test');

// Test non-alphanumeric characters
result = magic8ball('Am I going to win the 🏆?');
console.assert(result !== '', 'Failed: Non-alphanumeric characters test');

// Test multiple questions
result = magic8ball('Will it rain today?; Am I going to win the lottery?');
console.assert(result !== '', 'Failed: Multiple questions test');

// Test incorrect input format
result = magic8ball('Will it rain today.');
console.assert(result !== '', 'Failed: Incorrect input format test');

// Test user typos
result = magic8ball('Will I get a prommotion?');
console.assert(result !== '', 'Failed: User typos test');

// Test inappropriate content
result = magic8ball('Am I going to hell?');
console.assert(result !== '', 'Failed: Inappropriate content test');

console.log('All tests passed!');

**Comment by christinakerying** [comment]
------------------------------------------------

const magic8Ball = require('./magic8Ball'); // Assuming that magic8Ball is the main module

describe('Magic 8 Ball Program', () => {

  test('should return a valid response for a valid input', () => {
    const validInput = "Will I have a good day today?";
    const response = magic8Ball.getResponse(validInput);
    expect(response).toMatch(/^(Yes|No|Maybe|Ask again later)$/);
  });

  test('should return an error message for invalid input', () => {
    const invalidInput = "This is not a valid question";
    const response = magic8Ball.getResponse(invalidInput);
    expect(response).toBe("Error: Invalid input. Please ask a yes-or-no question.");
  });

  test('should handle unexpected input format', () => {
    const unexpectedInput = "WILL I WIN THE LOTTERY?";
    const response = magic8Ball.getResponse(unexpectedInput);
    expect(response).toMatch(/^(Yes|No|Maybe|Ask again later)$/i);
  });

  test('should handle a large number of questions without performance issues', () => {
    const input = "Will I have a good day today?";
    for (let i = 0; i < 1000; i++) {
      const response = magic8Ball.getResponse(input);
      expect(response).toMatch(/^(Yes|No|Maybe|Ask again later)$/);
    }
  });

  test('should handle internationalization', () => {
    const input = "今天我会赢得比赛吗？"; // Chinese: "Will I win the game today?"
    const response = magic8Ball.getResponse(input);
    expect(response).toMatch(/^(是|否|可能|再问)$/);
  });

  test('should handle customized answers', () => {
    const customAnswers = ["Definitely", "Absolutely not", "Outlook hazy"];
    const input = "Will I get a promotion?";
    const response = magic8Ball.getResponse(input, customAnswers);
    expect(response).toMatch(/^(Definitely|Absolutely not|Outlook hazy)$/);
  });

  test('should provide a mix of positive and negative responses even when input is biased', () => {
    const biasedInput = "Will the answer be yes?";
    const responses = [];
    for (let i = 0; i < 10; i++) {
      const response = magic8Ball.getResponse(biasedInput);
      responses.push(response);
    }
    const numYes = responses.filter(r => r === "Yes").length;
    const numNo = responses.filter(r => r === "No").length;
    expect(numYes).toBeGreaterThan(0);
    expect(numNo).toBeGreaterThan(0);
  });

});

Note that the above tests assume that the magic8Ball module exports a getResponse function that takes a string input (a yes-or-no question) and an optional array of custom answers, and returns a string response (a yes, no, maybe, or ask again later answer).
