### ISSUE TITLE
Research Documentation Format

### ISSUE THREAD

**Issue by ZettabytesCode** [cse110-sp23-group14/cse110-sp23-group14#27]
Research how we should preform documentation whether that be 

- Markdown files
- Github Wikis
- Other Documentation formats

Also research how user facing documentation is done/what to include. Some examples of user facing docs are:

- FAQs
- About us page
- etc.

**Comment by Mive667** [comment]
Markdown is good enough.

For the contenet we might include:
-  Introduction: Give an overview of our app, including its purpose and benefits.
- Quick Start: How to get started with this product quickly.
- Trouble Shooting(?): may be included in FAQs.
- Glossary: Explain some of the basic terms that appear in horoscopes(e.g. something in https://www.astrology.com/learn).

**Comment by Mive667** [comment]
Also,
Step-by-step instructions: Break down a task(set birthday, view and share horoscope, compatibility checker) into smaller, manageable steps. And provide screenshots or diagrams(by draw.io) .
