### ISSUE TITLE
Research on Progressive Web Apps

### ISSUE THREAD

**Issue by ZettabytesCode** [cse110-sp23-group14/cse110-sp23-group14#28]
Research how we would convert an app to a progressive web app:

- How easy is it to convert?
- Do we need any libraries to do it?
- Are there any issues with progressive web apps that we should be aware of

**Comment by mary7hu** [comment]
(recording the research prested to the team here)

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames
This gives an example on PWA website with source code.

In this example, there are main three parts to implement for PWA: make it offline (probably using Chach API), installable, and notification/push. Based on the source code provided in the example, it's reasonable to first set up a normal functional website with HTML, CSS, and javascript functioning together, and after that add PWA aspects one by one to the code.

Based on the research, PWA can be set as the next step for our project, but we can first test it out with our 8-ball website to see how viable it is and how much work it needs to take.
