### ISSUE TITLE
Write Horoscope Briefings / Calculation Algorithm

### ISSUE THREAD

**Issue by Viridian01** [cse110-sp23-group14/cse110-sp23-group14#34]
Research what the daily horoscope briefing would present to users given their personal information (zodiac sign etc.) and the conditions of the day (planet movements, constellations, etc.).

Ideally, this would be presented as a spreadsheet/chart grid where the columns are the conditions and the rows are the different zodiacs.

**Comment by ZettabytesCode** [comment]
Research complete: https://docs.google.com/spreadsheets/d/1hmyVIkx-Ni3zigpddrDiSwgJNcNyRPdaVqnNCJ7z3YA/edit?usp=sharing
