### ISSUE TITLE
Write Horoscope Share Copy Text

### ISSUE THREAD

**Issue by ZettabytesCode** [cse110-sp23-group14/cse110-sp23-group14#39]
Write a prompt for sharing your daily horoscope with others via copying text. Main idea is that these should be like the wordle share. A short and sweet copy pastable text that shares your horoscope/zodiac sign.

Prompt should include:

- Text about what the horoscopeis
- Include Zodiac sign
- Make sure text can be shared on a multitude of platforms (i.e twitter has character limit)
- Include emojis :)
- Feel free to add anything else you want

Extensions:

- Research how to use javascript can be used to copy text to clipboard and write a small demo of how you would do that

**Comment by christinakerying** [comment]
Hey [friend's name] 💖, I just checked my daily horoscope ✨and I couldn't wait to share it with you! According to the stars 🌌, for [Tauruses] [♉], [insert brief horoscope prediction for your zodiac sign]. How about you? Open our app and check your own forecast🌤, and let's compare our results📈. Who knows what the universe has in store for us today!

**Comment by christinakerying** [comment]
<button id="copy-button">Copy Text</button>
<textarea id="copy-text">Text to be copied to clipboard</textarea>

<script>
  const copyButton = document.querySelector('#copy-button');
  const copyText = document.querySelector('#copy-text');

  copyButton.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(copyText.value);
      alert('Copied to clipboard');
    } catch (err) {
      console.error('Failed to copy text: ', err);
    }
  });
</script>
