### ISSUE TITLE
Start writing js code for local storage of name + birthday

### ISSUE THREAD

**Issue by ZettabytesCode** [cse110-sp23-group14/cse110-sp23-group14#51]
Write some js code that allows you add a name + birthday to local storage for the fortunes 

- Work on fortune-telling-dev branch
- Can make a button + text area in settings.html
- Html does not have to be styled for now by try to make it in a way that style can be easily added
- Make sure you can add + edit
- Write unit tests in jest
- write JSDoc comments

**Comment by wengthree1cm** [comment]
Added button to edit or clear the name and birthday in `setting.html` and added coresponding functions in `home-scripts.js` file.
Added JSDoc comment for `home-scripts.js` and `serviceworker.js` file. 

need to figure out how to use jest test to test function involving with localstorage.

**Comment by wengthree1cm** [comment]
Two features are finished. And they are functional and working correctly.
