### ISSUE TITLE
Refactor fortune-telling-dev

### ISSUE THREAD

**Issue by ZettabytesCode** [cse110-sp23-group14/cse110-sp23-group14#57]
Need to do a refactor of code in the 

- Organize the files in the source files in repositories for scripts and assets and such
- make code more readable
- Fix naming conventions
- Add comments

**Comment by Mive667** [comment]
I pack some if-blocks into function in setting.js, and add JSDoc for these 2 functions, I'm not sure if this style is what we want.

**Comment by ZettabytesCode** [comment]
Finished 1st round by jim
